apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-image-updater-zot-creds
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: argocd-image-updater-zot-creds
    creationPolicy: Owner
    template:
      data:
        creds: "ci:{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: homelab/argocd-image-updater
        property: ZOT_CI_PASSWORD
